CREATE OR REPLACE VIEW SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.EMPLOYEE_PROJECT_SUMMARY(
	EMPLOYEE_NAME,
	PROJECT_NAME,
	WORK_DATE,
	HOURS_WORKED
) AS
SELECT 
  E.FIRST_NAME || 'M ' || E.LAST_NAME AS EMPLOYEE_NAME,
  P.PROJECT_NAME,
  T.WORK_DATE,
  T.HOURS_WORKED
FROM SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.TIMESHEETS T
JOIN SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.EMPLOYEES E ON T.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.PROJECTS P ON T.PROJECT_ID = P.PROJECT_ID;
