create or replace TABLE EMPLOYEES (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DEPARTMENT_ID NUMBER(38,0),
	JOIN_DATE DATE,
	primary key (EMPLOYEE_ID),
	foreign key (DEPARTMENT_ID) references SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.DEPARTMENTS(DEPARTMENT_ID)
);;

