CREATE OR REPLACE TABLE DEMO_DB.DATA_PIPELINE.EMPLOYEES (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DEPARTMENT_ID NUMBER(38,0),
	JOIN_DATE DATE,
	PRIMARY KEY (EMPLOYEE_ID),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEMO_DB.DATA_PIPELINE.DEPARTMENTS(DEPARTMENT_ID)
);
