create or replace TABLE SALARIES (
	EMPLOYEE_ID NUMBER(38,0),
	BASE_SALARY FLOAT,
	BONUS FLOAT,
	EFFECTIVE_DATE DATE,
	foreign key (EMPLOYEE_ID) references SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.EMPLOYEES(EMPLOYEE_ID)
);;

