create or replace TABLE SALARY_HISTORY (
	ENTRY_ID NUMBER(38,0) NOT NULL,
	EMPLOYEE_ID NUMBER(38,0),
	CHANGE_DATE DATE,
	OLD_SALARY NUMBER(18,2),
	NEW_SALARY NUMBER(18,2),
	primary key (ENTRY_ID),
	foreign key (EMPLOYEE_ID) references SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.EMPLOYEES(EMPLOYEE_ID)
);;

