create or replace TABLE TIMESHEETS (
	TIMESHEET_ID NUMBER(38,0) NOT NULL,
	EMPLOYEE_ID NUMBER(38,0),
	PROJECT_ID NUMBER(38,0),
	WORK_DATE DATE,
	HOURS_WORKED NUMBER(5,2),
	primary key (TIMESHEET_ID),
	foreign key (EMPLOYEE_ID) references SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.EMPLOYEES(EMPLOYEE_ID),
	foreign key (PROJECT_ID) references SNOWFLAKE_LEARNING_DB.DATA_PIPELINE.PROJECTS(PROJECT_ID)
);;

