-- Create schema
CREATE SCHEMA IF NOT EXISTS DATA_PIPELINE;

-- Create a customer table
CREATE OR REPLACE TABLE DATA_PIPELINE.CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME STRING,
    EMAIL STRING
);

-- Create a products table
CREATE OR REPLACE TABLE DATA_PIPELINE.PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME STRING,
    PRICE NUMBER(14, 2)
);

-- Create an orders table
CREATE OR REPLACE TABLE DATA_PIPELINE.ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES DATA_PIPELINE.CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DATA_PIPELINE.PRODUCTS(PRODUCT_ID)
);

-- Create stored procedure to update order record
CREATE OR REPLACE PROCEDURE DATA_PIPELINE.UPDATE_ORDER()
RETURNS STRING
LANGUAGE SQL
AS
'
BEGIN
    -- Update the order record
return ''success'';
END
';