-- Create schema
CREATE SCHEMA DATA_PIPELINE IF NOT EXISTS;

-- Create a customer table
CREATE OR REPLACE TABLE DATA_PIPELINE.CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME STRING,
    EMAIL STRING
);

-- Create a products table
CREATE OR REPLACE TABLE DATA_PIPELINE.PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME STRING,
    PRICE NUMBER(10, 2)
);

-- Create an orders table
CREATE OR REPLACE TABLE DATA_PIPELINE.ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES DATA_PIPELINE.CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DATA_PIPELINE.PRODUCTS(PRODUCT_ID)
);